<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="4" failures="1" disabled="0" errors="0" timestamp="2017-12-04T17:02:02" time="0.004" name="AllTests">
  <testsuite name="UnitTest" tests="4" failures="1" disabled="0" errors="0" time="0.002">
    <testcase name="additionner1" status="run" time="0" classname="UnitTest" />
    <testcase name="additionner2" status="run" time="0" classname="UnitTest" />
    <testcase name="additionner3" status="run" time="0" classname="UnitTest" />
    <testcase name="additionner4" status="run" time="0.001" classname="UnitTest">
      <failure message="c:\users\maxim\desktop\igl601tp4\test\test\test.cpp:34&#x0A;      Expected: 5&#x0A;To be equal to: x&#x0A;      Which is: 0" type=""><![CDATA[c:\users\maxim\desktop\igl601tp4\test\test\test.cpp:34
      Expected: 5
To be equal to: x
      Which is: 0]]></failure>
    </testcase>
  </testsuite>
</testsuites>
